accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('', views.index, name='index'),
    path('play/', views.play_puzzle, name='play_puzzle'),
    path('solved/', views.solved_puzzles, name='solved_puzzles'),
]

mureok/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('home/', views.home, name='home'),
    path('test/', views.test, name='test'),
    path('search/',views.search, name='search'),
    path('admin/', admin.site.urls),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('communities/', include('communities.urls')),
    path('gardens/', include('gardens.urls')),
    path('plants/', include('plants.urls')),
    path('sales/', include('sales.urls')),
    path('managements/', include('managements.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('game/', include('game.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:product_pk>/update/', views.update, name="update"),
    path('<int:product_pk>/delete/', views.delete, name="delete"),
    path('<int:product_pk>/like/', views.like, name='like'),
    path('detail/<int:product_pk>', views.detail, name="detail"),
    path('filter/', views.filter, name="filter"),
    # path('sort/', views.sort, name="sort"),

    path('cart/', views.cart, name="cart"),
    path('add-to-cart/<int:product_pk>/',views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_pk>/', views.remove_from_cart, name='remove_from_cart'),
    
    path('<int:product_pk>/review/create/', views.create_review, name='create_review'),
    path('<int:product_pk>/reviews/<int:review_pk>/delete_review/', views.delete_review, name='delete_review'),
    path('<int:product_pk>/reviews/<int:review_pk>/update_review/', views.update_review, name='update_review'),

    path('order_payment/<int:order_pk>/', views.order_payment, name="order_payment"),
    path('delete_order/<int:order_pk>/', views.delete_order, name='delete_order'),


    path('create_order/', views.create_order, name='create_order'),
    path('create_ordernow/<int:product_pk>', views.create_ordernow, name='create_ordernow'),

    path('order_complete', views.order_complete, name='order_complete'),
    path('order/<str:order_number>/', views.order_detail, name='order_detail'),

    path('order_list/', views.order_list, name='order_list'),
]

sales/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFit
from django.utils import timezone
from datetime import timedelta,datetime
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager
import random
def sale_img_path(instance, filename):
    return f'images/sale/{instance.title}/{filename}'
# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = CKEditor5Field('Content', config_name='extends')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_products')
    category = models.CharField(max_length=20)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    photo = models.ImageField(upload_to=sale_img_path)
    Thumbnail = ImageSpecField( 
		source = 'photo', 		  
		processors = [Thumbnail(300, 300)], 
		format = 'JPEG',		   
		options = {'quality': 90}) 
    
    def __str__(self):
        return self.title
    

# 주문정보
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    delivery_address = models.CharField(max_length=100)
    product_name = models.CharField(max_length=50)
    payment_status = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    order_number = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return f"주문번호 {self.order_number}"

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self.generate_order_number()
        super().save(*args, **kwargs)

    def generate_order_number(self):
        length = 10
        order_number = str(random.randint(0, 9999999999)).zfill(length)
        return order_number
    
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    title = models.CharField(max_length=20)
    score = models.IntegerField()
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def review_images_path(instance, filename):
        return f'reviews/{instance.title}/{filename}'
    image = ProcessedImageField(
        upload_to=review_images_path, 
        processors=[ResizeToFit(800, 800)], 
        format='JPEG',
        options={'quality': 100}
    )

    @property
    def created_time(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False

sales/views.py
from django.shortcuts import render, redirect
from .models import Product, Review, Order
from .forms import ProductForm, ReviewForm, OrderForm
# from .forms import PurchaseForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from accounts.models import User, User_title, User_profile
from django.db.models import Count, Q
from django.http import JsonResponse
from decimal import Decimal
from django.core import serializers
from django.views.generic import ListView
# csrf 권한 해제
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


def index(request):
    # 베스트 프로덕트(리뷰순)
    products = Product.objects.all().order_by('-created_at')
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'products': products,
        'page_obj': page_obj,
        'room_name': "broadcast",
    }
    return render(request, 'sales/index.html', context)


@login_required
def create(request):
    if not request.user.is_superuser:
        return redirect('home')
    
    if request.method == 'POST':
        tags = request.POST.get('tags').split(',')
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()

            for tag in tags:
                product.tags.add(tag.strip())
            return redirect('sales:detail', product.pk)
    else:
        form = ProductForm()
    
    context = {
        'form' : form,
        'room_name': "broadcast"
    }
    return render(request, 'sales/create.html', context)


@login_required
def like(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if product.like_users.filter(pk=request.user.pk).exists():
        product.like_users.remove(request.user)
        is_liked = False
    else:
        product.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
        'like_count': product.like_users.count(),
    }
    return JsonResponse(context)


def detail(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    reviews = product.reviews.all()
    # products = Product.objects.all().order_by('like')

    if request.method =='POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.product = product
            review.user = request.user
            review.score = request.POST.get('score')
            review.save()
    else:
        review_form = ReviewForm()
    context ={
        'product': product,
        'reviews': reviews,
        'review_form': review_form,
        'room_name': "broadcast"
    }
    return render(request,'sales/detail.html', context)


def filter(request):
    category = request.GET.getlist('category')
    low_price = request.GET.get('low_price', 0)
    high_price = request.GET.get('high_price', None)

    if low_price:
        low_price = int(low_price)
    if high_price:
        high_price = int(high_price)

    if category:
        products = Product.objects.filter(category__in=category)
    else:
        products = Product.objects.all()

    if low_price or high_price:
        price_filter = Q()
        if low_price:
            price_filter &= Q(price__gte=low_price)
        if high_price:
            price_filter &= Q(price__lte=high_price)
        products = products.filter(price_filter).distinct()

    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'products': products,
        'category': category,
        'low_price': low_price,
        'high_price': high_price,
        'page_obj': page_obj,
        'room_name': "broadcast",
    }
    return render(request, 'sales/filter.html', context)


# def sort(request, *args, **kwargs):
#     sort_type = request.GET.get('sort_type')
#     queryset = super().get_queryset()

#     if sort_type == 'popularity':
#         queryset = queryset.order_by('-views')
#     elif sort_type == 'latest':
#         queryset = queryset.order_by('-created_at')
#     elif sort_type == 'price_low':
#         queryset = queryset.order_by('price')
#     elif sort_type == 'price_high':
#         queryset = queryset.order_by('-price')

#     data = serializers.serialize('json', queryset)

#     paginator = Paginator(data, 16)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)

#     context = {
#         'page_obj': page_obj,
#         'room_name': "broadcast",
#     }
#     return JsonResponse(context, safe=False)


@login_required
def update(request, product_pk):
    if not request.user.is_superuser:
        return redirect('home')

    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            product.tags.clear()
            tags = request.POST.get('tags').split(',')
            for tag in tags:
                product.tags.add(tag.strip())
            return redirect('sales:detail', product.pk)
    else:
        form = ProductForm(instance=product)
    context = {
        'product': product,
        'form' : form,
        'room_name': "broadcast",
    }
    return render(request,'sales/update.html', context)


@login_required
def delete(request, product_pk):

    if not request.user.is_superuser:
        return redirect('home')
    
    product = Product.objects.get(pk=product_pk)
    if request.user == product.user:
        product.delete()
    return redirect('sales:index')


@login_required
def delete_review(request, product_pk, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        review.delete()

        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'error', 'message': '권한이 없습니다.'})


@login_required
def update_review(request, product_pk, review_pk):
    product = Product.objects.get(pk=product_pk)
    review = Review.objects.get(pk=review_pk)
    
    if request.user != review.user:
        return redirect('sales:detail', product_pk)
    
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('sales:detail', product_pk)
    else:
        form = ReviewForm(instance=review)
    
    context = {
        'product': product,
        'review': review,
        'form': form,
        'room_name': "broadcast"
    }
    return render(request, 'sales/detail.html', context)


# def delete(request, product_pk):
#     product = Product.objects.get(pk=product_pk)
#     if request.user == product.user:
#         product.delete()
#     return redirect('sales:index')


@login_required 
def create_review(request, product_pk):
    product = Product.objects.get(pk = product_pk)
    
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.score = request.POST.get('score')
            review.product = product
            review.save()
            return redirect('sales:detail', product_pk)
    else:
        review_form = ReviewForm()
    context = {
        'product': product,
        'review_form': review_form,
        'room_name': "broadcast",
    }
    return render(request, 'sales/detail.html', context)


def add_to_cart(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    quantity = int(request.POST.get('quantity', 1))
    cart = request.session.get('cart', {})
    if product_pk in cart:
        cart[product_pk]['quantity'] += quantity
    else:
        cart[product_pk] = {'quantity': quantity, 'price': str(product.price), 'product_pk': product.pk}

    request.session['cart'] = cart

    return redirect('sales:cart')


def cart(request):
    cart = request.session.get('cart', {})
    cart_items = []
    cart_total = 0
    for product_pk, product_info in cart.items():
        product = Product.objects.get(pk=product_pk)
        total_price = (product_info['quantity']) * product.price
        cart_total += total_price

        cart_items.append({
            'product': product,
            'quantity': product_info['quantity'],
            'total_price': total_price,
        })

    context = {
        'cart_items': cart_items,
        'cart_total': cart_total,
        'room_name': "broadcast"

    }
    return render(request, 'sales/cart.html', context)


def remove_from_cart(request, product_pk):
    cart = request.session.get('cart', {})
    product_pk = str(product_pk)

    if product_pk in cart:
        del cart[product_pk]
        request.session['cart'] = cart

        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'error', 'message': '권한이 없습니다.'})


def create_order(request):
    cart = request.session.get('cart', {})
    cart_items = []
    cart_total = 0
    cart_total_quantity = 0
    cart_product = ''
    for product_pk, product_info in cart.items():
  
        product = Product.objects.get(pk=product_pk)
        total_price = (product_info['quantity']) * product.price
        cart_total += total_price
        cart_total_quantity += product_info['quantity']
        cart_product += product.title + ' '

        cart_items.append({
            'product': product,
            'quantity': product_info['quantity'],
            'total_price': total_price,
            'cart_product':cart_product,
        })
        print(cart_items)

sales/templates/sales/create_order.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>주문하기</title>
{% endblock head %}


{% block content %}
<main>
  <div class="sm:hidden h-14 px-2 flex items-center">
    <div class="flex flex-shrink-0 items-center gap-4">
        <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
        <p class="text-xl h-8 w-auto"><b>그린샵</b></p>
    </div>
  </div>
  <div class="mx-auto max-w-7xl px-2 sm:px-36 sm:min-h-[700px]">
    <h1 class="text-center text-[25px] font-semibold my-12">주문하기</h1>
    <form method="post" action="{% url 'sales:create_order' %}" class="mx-auto sm:px-[200px] mb-16">
      {% csrf_token %}
      
      <!-- 장바구니 상품 정보 -->
      <div class="mb-4">
        <label for="product_name" class="block font-medium text-sm text-gray-700">상품명</label>
        <input type="text" id="product_name" name="product_name" value="{{cart_product}}" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
      
      <div class="mb-4">
        <label for="quantity" class="block font-medium text-sm text-gray-700">수량</label>
        <input type="text" id="quantity" name="quantity" value="{{cart_total_quantity}}" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
    
      <div class="mb-4">
        <label for="price" class="block font-medium text-sm text-gray-700">금액</label>
        <input type="text" id="price" name="price" value="{{cart_total }}" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
    
      <!-- 배송 주소 입력 필드 -->
      <div class="mb-4">
        <div class="flex justify-end">
        </div>
        <label for="id_delivery_address" class="block font-medium text-sm text-gray-700">배송 주소</label>
        <input type="text" name="delivery_address" id="id_delivery_address" class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md"  required>
        
      </div>
      
      <!-- 주문하기 버튼 -->
      <button type="submit" class="w-full px-4 py-2 mt-8 text-sm font-medium text-white bg-[#1EB564] rounded-md hover:bg-blue-600" >주문하기</button>
    </form>
  </div>
</main>
{% endblock content %}


{% block script %}
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
  window.onload = function(){
    document.getElementById("id_delivery_address").addEventListener("click", function(){ //주소입력칸을 클릭하면
        //카카오 지도 발생
        new daum.Postcode({
            oncomplete: function(data) { //선택시 입력값 세팅
                document.getElementById("id_delivery_address").value = data.address; // 주소 넣기
            }
        }).open();
    });
}
</script>
{% endblock script %}

sales/templates/sales/create_ordernow.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>주문하기</title>
{% endblock head %}


{% block content %}
<main>
  <div class="sm:hidden h-14 px-2 flex items-center">
    <div class="flex flex-shrink-0 items-center gap-4">
        <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
        <p class="text-xl h-8 w-auto"><b>그린샵</b></p>
    </div>
  </div>
  <div class="mx-auto max-w-7xl px-2 sm:px-36 sm:min-h-[700px]">
    <h1 class="text-center text-[25px] font-semibold my-12">주문하기</h1>
    <form method="post" action="{% url 'sales:create_ordernow' product.pk %}" class="mx-auto sm:px-[200px] mb-16">
      {% csrf_token %}
      
      <!-- 장바구니 상품 정보 -->
      <div class="mb-4">
        <label for="product_name" class="block font-medium text-sm text-gray-700">상품명</label>
        <input type="text" id="product_name" name="product_name" value="{{ product.title }}" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
      
      <div class="mb-4">
        <label for="quantity" class="block font-medium text-sm text-gray-700">수량</label>
        <input type="text" id="quantity" name="quantity" value="1" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
    
      <div class="mb-4">
        <label for="price" class="block font-medium text-sm text-gray-700">금액</label>
        <input type="text" id="price" name="price" value="{{ product.price }}" readonly class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md">
      </div>
    
      <!-- 배송 주소 입력 필드 -->
      <div class="mb-4">
        <div class="flex justify-end">
        </div>
        <label for="id_delivery_address" class="block font-medium text-sm text-gray-700">배송 주소</label>
        <input type="text" name="delivery_address" id="id_delivery_address" class="w-full px-3 py-2 mt-1 text-gray-700 bg-gray-100 rounded-md"  required>
        
      </div>
      
      <!-- 주문하기 버튼 -->
      <button type="submit" class="w-full px-4 py-2 mt-8 text-sm font-medium text-white bg-[#1EB564] rounded-md hover:bg-blue-600" >주문하기</button>
    </form>
  </div>
</main>
{% endblock content %}


{% block script %}
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
  window.onload = function(){
    document.getElementById("id_delivery_address").addEventListener("click", function(){ //주소입력칸을 클릭하면
        //카카오 지도 발생
        new daum.Postcode({
            oncomplete: function(data) { //선택시 입력값 세팅
                document.getElementById("id_delivery_address").value = data.address; // 주소 넣기
            }
        }).open();
    });
}
</script>
{% endblock script %}

sales/templates/sales/order_list.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>나의 주문목록</title>
{% endblock head %}


{% block content %}
{% comment %} 가로로 넘치면 스크롤 {% endcomment %}
<main>
    <div class="sm:hidden h-14 px-2 flex items-center">
        <div class="flex flex-shrink-0 items-center gap-4">
            <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
            <p class="text-xl h-8 w-auto"><b>그린샵</b></p>
        </div>
    </div>
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="font-bold text-[20px] sm:text-[25px] mt-5 sm:mt-16 mb-8">나의 주문목록</div>
        {% if orders %}
    
        {% comment %} min-w-full 최소 가로 너비 100%  / 분할선 divide-y{% endcomment %}
            <table class="hidden sm:table w-full">
                <thead>
                    <tr class="border-b-2 border-[#1EB564]">
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            주문 번호
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            주문 일자
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            배송 주소
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            상품명
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            배송 상태
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            수량
                        </th>
                        <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            가격
                        </th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% for order in orders %}
                    <tr>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.order_number }}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.order_date }}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.delivery_address }}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.product_name }}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {% if order.payment_status %}
                            배송 시작!!
                            {% else %}
                            배송 준비중
                            {% endif %}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.quantity }}
                        </td>
                        <td class="px-6 py-4 whitespace-no-wrap">
                            {{ order.price }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% comment %} 모바일 버전 {% endcomment %}
            <div class="sm:hidden flex flex-col gap-3 w-full min-h-[300px]">
                {% for order in orders %}
                <div class="border p-3 rounded-lg">
                    <p class="text-[#1EB564] mb-3">{% if order.payment_status %}
                        배송 시작!!
                        {% else %}
                        배송 준비중
                        {% endif %}
                    </p>
                    <img src="{{ order.image.url }}" alt="">
                    <p>주문번호 : {{ order.order_number }}</p>
                    <p class="text-[14px] text-gray-500">{{ order.order_date }}</p>
                    <p class="text-[14px] mb-3">{{ order.delivery_address }}</p>
                    <p class="font-semibold text-[20px]">{{ order.product_name }}</p>
                    <div class="flex justify-between">
                        <p class="text-[18px]">{{ order.price }}원</p>
                        <a href="{% url 'sales:order_detail' order.order_number %}">
                            <div class="border rounded-md p-1 px-2 text-[14px]">상세보기</div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
        <table class="hidden sm:table w-full">
            <thead>
                <tr class="border-b-2 border-[#1EB564]">
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        주문 번호
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        주문 일자
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        배송 주소
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        상품명
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        배송 상태
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        수량
                    </th>
                    <th class="px-6 py-3 bg-gray-50 text-left text-sm leading-4 font-medium text-gray-500 uppercase tracking-wider">
                        가격
                    </th>
                </tr>
            </thead>
        </table>
        <div class="flex items-center justify-center mt-3">
            <p>주문 상품이 없습니다.</p>
        </div>
        {% endif %}
        <div class="flex justify-center">
            <button class="mt-[50px] mb-16 block text-center bg-white border border-[#1EB564] text-[#1EB564] rounded-md px-4 py-2 hover:bg-[#1EB564] hover:text-white mx-auto w-40 h-15"><a href="{% url 'accounts:profile' user.username %}">돌아가기</a></button>
        </div>
    </div>
</main>
{% endblock content %}