accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('', views.index, name='index'),
    path('play/', views.play_puzzle, name='play_puzzle'),
    path('solved/', views.solved_puzzles, name='solved_puzzles'),
]

mureok/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('home/', views.home, name='home'),
    path('test/', views.test, name='test'),
    path('search/',views.search, name='search'),
    path('admin/', admin.site.urls),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('communities/', include('communities.urls')),
    path('gardens/', include('gardens.urls')),
    path('plants/', include('plants.urls')),
    path('sales/', include('sales.urls')),
    path('managements/', include('managements.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('game/', include('game.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFit
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    birthday = models.DateField(null=True)
    image = ProcessedImageField(upload_to='users', 
                                blank=True,
                                processors=[Thumbnail(100,100)],
                                format='JPEG',
                                options={'quality': 80})




class User_title(models.Model):
    name = models.CharField(max_length=20)
    min_points = models.IntegerField()
    max_points = models.IntegerField()

    def __str__(self):
        return self.name


class User_profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    points = models.IntegerField(default=0)
    title = models.ForeignKey(User_title, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from django.forms.widgets import NumberInput

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='사용자 ID',
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-100 rounded-lg p-2 ps-4 w-full focus:outline-none focus:ring-1 focus:ring-[#1EB564] m-0',
                'id': '사용자 ID',
                'placeholder': '아이디를 입력해주세요',
            }
        )
    )
    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'bg-gray-100 rounded-lg p-2 ps-4 w-full focus:outline-none focus:ring-1 focus:ring-[#1EB564] m-0',
                'id': '비밀번호',
                'placeholder': '비밀번호를 입력해주세요',
            }
        )
    )

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='사용자 ID',
        widget=forms.TextInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id': '사용자 ID',
            }
        )
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id': '비밀번호',
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id': '비밀번호 확인',
            }
        )
    )
    email = forms.CharField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id': '이메일',
            }
        )
    )
    image = forms.ImageField(
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'border rounded-md w-full focus:outline-none focus:ring-1 focus:ring-[#1EB564] text-[14px]',
            },
        ),
        required=False,
    )
    birthday = forms.DateTimeField(
        label="날짜",
        widget=NumberInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'type': 'date',
            },
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username', 'password1', 'password2', 'email','image',
        )


class CustomUserChangeForm(UserChangeForm):
    email = forms.CharField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id' : '이메일',
            }
        )
    )

    image = forms.ImageField(
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'border rounded-md w-full focus:outline-none focus:ring-1 focus:ring-[#1EB564] text-[14px]',
                'id' : 'id_image',
            },
        ),
        required=False,
    )

    password = None
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email','image',)


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='기존 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id' : '기존 비밀번호',
            },
        ),
    )
    new_password1= forms.CharField(
        label='새 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id' : '새 비밀번호',
            },
        ),
    )
    new_password2 = forms.CharField(
        label='새 비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'border rounded-md p-2 ps-3 w-full h-8 focus:outline-none focus:ring-1 focus:ring-[#1EB564]',
                'id' : '새 비밀번호 확인',
            },
        ),
    )   

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse
from django.urls import reverse
from .models import User_profile, User_title

def login(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            prev_url = request.session.get('prev_url')
            # 이전 페이지의 URL 정보가 있으면 해당 URL로 리다이렉트합니다.
            if prev_url:
                # 이전 페이지의 URL 정보를 삭제합니다.
                del request.session['prev_url']
                return redirect(prev_url)
            return redirect('home')
    else:
        form = CustomAuthenticationForm()
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    context = {
        'form': form,
        'room_name': "broadcast"
    }
    return render(request, 'accounts/login.html', context)



@login_required
def logout(request):
    auth_logout(request)
    request.session['prev_url'] = request.META.get('HTTP_REFERER')

    # 로그아웃 후 이전 페이지의 URL 정보가 있으면 해당 페이지로 리다이렉트합니다.
    prev_url = request.session.get('prev_url')
    if prev_url:
        # 이전 페이지의 URL 정보를 삭제합니다.
        del request.session['prev_url']
        return redirect(prev_url)
        
    return redirect('home')



def signup(request):
    if request.user.is_authenticated:
        return redirect('home')


    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()  # User 객체 저장
            user_profile = User_profile.objects.create(user=user)
            user_profile.points = 0

            min_points = user_profile.points
            max_points = user_profile.points
            user_title = User_title.objects.filter(min_points__lte=min_points, max_points__gte=max_points).first()
            user_profile.title = user_title


            user_profile.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            prev_url = request.session.get('prev_url')
            if prev_url:
                del request.session['prev_url']
                return redirect(prev_url)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    context = {
        'form': form,
        'room_name': "broadcast"
    }
    return render(request, 'accounts/signup.html', context)



@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('home')



@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'room_name': "broadcast"
    }
    return render(request, 'accounts/update.html', context)



@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', request.user)
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
        'room_name': "broadcast"
    }
    return render(request, 'accounts/change_password.html', context)



def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)

    
    context = {
        'person': person,
        'room_name': "broadcast",
        'user_profile': user_profile
    }
    return render(request, 'accounts/profile.html', context)



@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)


@login_required
def user_profile(request):
    user_profile = User_profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'user_profile': user_profile})

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>비밀번호 변경</title>
{% endblock head %}


{% block content %}
<main class="bg-gray-100 h-screen flex">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="sm:hidden h-14 px-2 flex items-center">
      <div class="flex flex-shrink-0 items-center gap-4">
          <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
          <p class="text-xl h-8 w-auto"><b>무럭무럭</b></p>
      </div>
    </div>
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="rounded-xl bg-white shadow-sm mx-auto p-8 mt-16 w-[350px]">
        <h1 class="text-center mb-8 text-[20px]"><b>비밀번호 수정</b></h1>
          <form action="{% url 'accounts:change_password' %}" method="POST" class="form-text" enctype = 'multipart/form-data'>
            {% csrf_token %}
            <div class="flex flex-col gap-3 mb-5">
              <div class="text-[14px]">{{ form.old_password.label }}</div>
              <div>{{ form.old_password }}</div>
            </div>
            <div class="flex flex-col gap-3 mb-5">
              <div class="text-[14px]">{{ form.new_password1.label }}</div>
              <div>{{ form.new_password1 }}</div>
            </div>
            <div class="flex flex-col gap-3 mb-5">
              <div class="text-[14px]">{{ form.new_password2.label }}</div>
              <div>{{ form.new_password2 }}</div>
            </div>
            <input type="submit" class="bg-[#1EB564] text-white rounded-md text-center w-full p-2 font-semibold cursor-pointer" value="비밀번호 수정">
          </form>
      </div>
  </div>
</main>
{% endblock content %}


{% block script %}{% endblock script %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>로그인</title>
{% endblock head %}


{% block content %}
<main class="bg-gray-100 min-h-[580px] sm:min-h-[720px] flex">
  <div class="mx-auto w-full px-2 sm:px-6 lg:px-8">
    <div class="sm:hidden h-14 px-2 flex items-center">
      <div class="flex flex-shrink-0 items-center gap-4">
          <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
          <p class="text-xl h-8 w-auto"><b>무럭무럭</b></p>
      </div>
    </div>
    <div class="rounded-xl bg-white shadow-sm mx-auto p-8 mt-16 w-[350px]">
      <div class="mb-5">
        <h1 class="text-[22px] text-center mb-3"><b>로그인</b></h1>
        <p class="text-center text-[14px]">아직 회원이 아니신가요? <a href="{% url 'accounts:signup' %}" class="text-[#1EB564]"><b>회원가입</b></a></p>
      </div>
      <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          <div class="flex flex-col gap-3 mb-5">
            <div class="text-[14px]">{{ form.username.label }}</div>
            <div>{{ form.username }}</div>
          </div>
          <div class="flex flex-col gap-3 mb-5">
            <div class="text-[14px]">{{ form.password.label }}</div>
            <div>{{ form.password }}</div>
          </div>
          <input type="submit" class="rounded-lg bg-[#1EB564] text-white w-full py-2 text-[16px] font-semibold" value="시작하기">
      </form>
  
      <div class="w-100 text-center mt-5">
          {% comment %} 소셜 로그인 부분입니다. {% endcomment %}
  
 
            {% load socialaccount %}
            <div class="flex flex-col items-center gap-5">
              <p class="text-[18px]"><b>소셜로그인</b></p>
              <div class="flex justify-evenly gap-5">
                <a href="{% provider_login_url 'kakao' method='oauth2' %}">
                  <div class="flex items-center p-4 border rounded-xl bg-white w-16 h-16">
                    <img src="{% static 'img/google_logo.png' %}" alt="">
                  </div>
                </a>
                <a href="{% provider_login_url 'kakao' method='oauth2' %}">
                  <div class="flex items-center p-4 rounded-xl bg-[#FFE24A] w-16 h-16">
                    <img src="{% static 'img/kakao_logo.png' %}" alt="">
                  </div>
                </a>
                <a href="{% provider_login_url 'naver' method='oauth2' %}">
                  <div class="flex items-center p-5 text-white rounded-xl bg-[#25D036] w-16 h-16 text-center">
                    <img src="{% static 'img/naver_logo.png' %}" alt="">
                  </div>
                </a>
              </div>
            </div>

      </div>
    </div>
  </div>
</main>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>회원가입</title>
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock head %}


{% block content %}
<main class="bg-gray-100 sm:min-h-screen flex">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="sm:hidden h-14 px-2 flex items-center">
      <div class="flex flex-shrink-0 items-center gap-4">
          <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
          <p class="text-xl h-8 w-auto"><b>무럭무럭</b></p>
      </div>
    </div>
      <div class="rounded-xl bg-white shadow-sm mx-auto p-8 mt-3 sm:mt-16 w-full">
        <div class="mb-5">
          <h1 class="text-center text-[20px] mb-3"><b>회원가입</b></h1>
          <p class="text-center text-[14px]">이미 회원이신가요? <a href="{% url 'accounts:login' %}" class="text-[#1EB564]"><b>로그인</b></a></p>
        </div>
          <form action="{% url 'accounts:signup' %}" method="POST" class="form-text" enctype = 'multipart/form-data'>
            {% csrf_token %}
            <div class="flex flex-col gap-1 mb-5">
              <div class="text-[14px]">{{ form.username.label }}</div>
              <div>{{ form.username }}</div>
            </div>
            <div class="flex flex-col gap-1 mb-5">
              <div class="text-[14px]">{{ form.password1.label }}</div>
              <div>{{ form.password1 }}</div>
            </div>
            <div class="flex flex-col gap-1 mb-5">
              <div class="text-[14px]">{{ form.password2.label }}</div>
              <div>{{ form.password2 }}</div>
            </div>
            <div class="flex flex-col gap-1 mb-5">
              <div class="text-[14px]">{{ form.email.label }}</div>
              <div>{{ form.email }}</div>
            </div>
            <div class="flex flex-col gap-1 mb-8">
              <div class="text-[14px]">{{ form.image.label }} <span class="text-[12px] text-gray-400">(Optional)</span></div>
              <div class="flex items-center gap-5">
                <div class="signup-image_wrapper border border-gray-400">
                  {% if form.image.url %}
                      <img id="preview" src="{{ form.image.url }}" alt="">
                  {% else %}
                      <img id="preview" src="{% static 'img/no_profile.jpg' %}" alt="">
                  {% endif %}
                </div>
                <div>{{ form.image }}</div>
              </div>
            </div>
            <div class="flex flex-col gap-1 mb-8">
              <div class="text-[14px]">{{ form.birthday.label }}</div>
              <div>{{ form.birthday }}</div>
            </div>
            <input type="submit" class="bg-[#1EB564] text-white rounded-md text-center w-full p-2 font-semibold cursor-pointer" value="회원가입">
          </form>
      </div>
  </div>
</main>
{% endblock content %}


{% block script %}
<script src="{% static 'js/signupPreview.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>회원정보 수정</title>
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock head %}


{% block content %}
<main class="bg-gray-100 h-screen flex">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="sm:hidden h-14 px-2 flex items-center">
      <div class="flex flex-shrink-0 items-center gap-4">
          <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
          <p class="text-xl h-8 w-auto"><b>무럭무럭</b></p>
      </div>
    </div>
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="rounded-xl bg-white shadow-sm mx-auto p-8 mt-16 w-full">
        <h1 class="text-center mb-8 text-[20px]"><b>회원정보 수정</b></h1>
          <form action="{% url 'accounts:update' %}" method="POST" class="form-text" enctype = 'multipart/form-data'>
            {% csrf_token %}
            {% comment %} 이메일 수정 {% endcomment %}
            <div class="flex flex-col gap-3 mb-5">
              <div class="text-[14px]">{{ form.email.label }}</div>
              <div>{{ form.email }}</div>
            </div>

            {% comment %} 프로필 사진 수정 {% endcomment %}
            <div class="flex flex-col gap-3 mb-8">
              <div class="text-[14px]">{{ form.image.label }} <span class="text-[12px] text-gray-400">(Optional)</span></div>
              <div class="flex items-center gap-5">
                <div class="signup-image_wrapper border border-gray-400">
                  {% if user.image %}
                      <img id="preview" src="{{ user.image.url }}" alt="">
                  {% else %}
                      <img id="preview" src="{% static 'img/no_profile.jpg' %}" alt="">
                  {% endif %}
                </div>
                <div>{{ form.image }}</div>
              </div>
            </div>
            <input type="submit" class="bg-[#1EB564] text-white rounded-md text-center w-full p-2 font-semibold cursor-pointer" value="회원정보 수정">
          </form>
          <a href="{% url 'accounts:change_password' %}">
            <p class="text-center mt-5 text-[14px] text-[#1EB564]">비밀번호 수정</p>
          </a>
      </div>
  </div>
</main>
{% endblock content %}


{% block script %}
<script src="{% static 'js/profileUpdatePreview.js' %}"></script>
{% endblock script %}