accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('', views.index, name='index'),
    path('play/', views.play_puzzle, name='play_puzzle'),
    path('solved/', views.solved_puzzles, name='solved_puzzles'),
]

gardens/urls.py
from django.urls import path
from . import views


app_name = "gardens"
urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:garden_pk>/delete/', views.delete, name='delete'),
    path('<int:garden_pk>/update/', views.update, name='update'),
    path('<int:garden_pk>/like_garden/', views.like_garden, name='like_garden'),
    path('listing/', views.listing, name='listing'),
    path('<int:garden_pk>/', views.detail, name='detail'),
    path('<int:garden_pk>/comment/', views.comment, name='comment'),
    path('<int:garden_pk>/comments/<int:comment_pk>/update/',views.comment_update, name='comment_update'),
    path('<int:garden_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # path('location/', views.location, name='location')
    path('search/', views.search, name='search'),
]

mureok/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('home/', views.home, name='home'),
    path('test/', views.test, name='test'),
    path('search/',views.search, name='search'),
    path('admin/', admin.site.urls),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('communities/', include('communities.urls')),
    path('gardens/', include('gardens.urls')),
    path('plants/', include('plants.urls')),
    path('sales/', include('sales.urls')),
    path('managements/', include('managements.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('game/', include('game.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plants/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'plants'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name = 'create'),
    path('<int:plant_pk>/update/', views.update, name = 'update'),
    path('<int:plant_pk>/delete/', views.delete, name = 'delete'),
    path('<int:plant_pk>/', views.detail, name='detail'),
    path('<int:plant_pk>/likes/', views.likes, name='likes'),

    path('search/', views.search, name='search'),
    path('filter-plants/<str:tag>/', views.filter_plants, name='filter_plants'),
    # path('filter-plants-ajax/', views.filter_plants_ajax, name='filter_plants_ajax'),

    path('recommendation/', views.recommendation, name='recommendation'),
    path('category/', views.category_plants, name='category'),
]

sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:product_pk>/update/', views.update, name="update"),
    path('<int:product_pk>/delete/', views.delete, name="delete"),
    path('<int:product_pk>/like/', views.like, name='like'),
    path('detail/<int:product_pk>', views.detail, name="detail"),
    path('filter/', views.filter, name="filter"),
    # path('sort/', views.sort, name="sort"),

    path('cart/', views.cart, name="cart"),
    path('add-to-cart/<int:product_pk>/',views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_pk>/', views.remove_from_cart, name='remove_from_cart'),
    
    path('<int:product_pk>/review/create/', views.create_review, name='create_review'),
    path('<int:product_pk>/reviews/<int:review_pk>/delete_review/', views.delete_review, name='delete_review'),
    path('<int:product_pk>/reviews/<int:review_pk>/update_review/', views.update_review, name='update_review'),

    path('order_payment/<int:order_pk>/', views.order_payment, name="order_payment"),
    path('delete_order/<int:order_pk>/', views.delete_order, name='delete_order'),


    path('create_order/', views.create_order, name='create_order'),
    path('create_ordernow/<int:product_pk>', views.create_ordernow, name='create_ordernow'),

    path('order_complete', views.order_complete, name='order_complete'),
    path('order/<str:order_number>/', views.order_detail, name='order_detail'),

    path('order_list/', views.order_list, name='order_list'),
]

templates/main.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>무럭무럭</title>
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock head %}


{% block content %}
<main>
    <section class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 h-screen flex flex-col justify-center relative">
        <div class="sm:flex sm:items-center sm:justify-between mb-6">
            {% comment %} 서비스 타이틀 영역 {% endcomment %}
            <div>
                <div class="mx-2 sm:mx-0 flex items-center gap-3 mt-10 sm:mt-0 mb-5 sm:mb-[50px]">
                    <img src="{% static 'img/logo.svg' %}" alt="" class="w-10 h-10 sm:w-[67px] sm:h-[67px]">
                    <h1 class="text-[35px] sm:text-[50px]"><b>무럭무럭</b></h1>
                </div>
                <div class="mx-2 sm:mx-0 mb-8 sm:mb-16 sm:mb-[100px] flex flex-col gap-4">
                    <p class="text-[20px] sm:text-[45px]"><b>당신의 식물은 어떤가요?</b></p>
                    <p class="text-[16px] sm:text-[25px]"><b>식물 정보부터 판매, 관리까지<br>식물에 대한 다양한 서비스를 한 번에</b></p>
                </div>
                <div class="hidden sm:flex sm:flex-col sm:gap-5">
                    <div class="p-3 px-5 border rounded-xl shadow-md w-fit text-[20px]">🤔 언제 얼마나 물을 주어야 하지?</div>
                    <div class="ms-[25%] p-3 px-5 border rounded-xl shadow-md w-fit text-[20px]">괜찮은 식물을 추천받고 싶어요!! 🤔</div>
                    <div class="ms-[10%] p-3 px-5 border rounded-xl shadow-md w-fit text-[20px]">🤔 화분을 사고 싶은데 어떤 걸 사지?</div>
                </div>
            </div>
    
            {% comment %} 로그인 영역 {% endcomment %}
            <div class="relative h-[500px] sm:h-min w-full sm:w-4/12 flex flex-col items-center gap-8 justify-center border rounded-[30px] p-8 sm:px-[60px] sm:pb-[60px] shadow-lg">
                <img src="{% static 'img/watering_plant.png' %}" alt="" class="absolute top-[-100px] hidden sm:block">

                {% comment %} 이미 로그인 된 유저인지 검증 {% endcomment %}
                {% if request.user.is_authenticated %}
                <div class="sm:mt-[65%] w-full flex flex-col items-center gap-5">
                    <div class="rounded-full profile-image_wrapper border-[0.5px] border-[#1EB564]">
                        {% if request.user.image %}
                            <img src="{{ request.user.image.url }}" alt="">
                        {% else %}
                            <img src="{% static 'img/no_profile.jpg' %}" alt="">
                        {% endif %}
                    </div>
                    <div>
                        <p class="text-[18px]"><b>{{ user.username }}님</b></p>
                    </div>
                    <a href="{% url 'home' %}" class="rounded-lg bg-[#1EB564] text-white text-center w-full py-2 text-[16px] font-semibold">홈으로 이동</a>
                    <a href="{% url 'accounts:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:text-black" role="menuitem" tabindex="-1" id="user-menu-item-2">로그아웃</a>
                </div>
                {% else %}
                <div class="sm:mt-[65%] w-full">
                    <h2 class="text-[22px] text-center mb-5"><b>로그인</b></h2>
                    <form action="{% url 'accounts:login' %}" method="POST" class="flex flex-col items-center gap-3 w-full">
                        {% csrf_token %}
                        <div class="w-full">{{ form.username }}</div>
                        <div class="w-full">{{ form.password }}</div>
                        <input type="submit" class="rounded-lg bg-[#1EB564] text-white w-full py-2 text-[16px] font-semibold" value="시작하기">
                    </form>
                </div>
    
                {% comment %} 회원가입 {% endcomment %}
                {% load socialaccount %}
                <div class="flex flex-col items-center sm:flex-row sm:gap-3">
                    <p>혹시 처음 방문하셨나요?</p>
                    <a href="{% url 'accounts:signup' %}" class="text-[#1EB564]"><b>회원가입</b></a>
                </div>
    
                {% comment %} 소셜로그인 {% endcomment %}
                <div class="flex flex-col items-center gap-5">
                    <p class="text-[18px]"><b>소셜로그인</b></p>
                    <div class="flex justify-evenly gap-5">
                        <a href="{% provider_login_url 'kakao' method='oauth2' %}">
                            <div class="flex items-center p-4 border rounded-xl bg-white w-16 h-16">
                                <img src="{% static 'img/google_logo.png' %}" alt="">
                            </div>
                        </a>
                        <a href="{% provider_login_url 'kakao' method='oauth2' %}">
                            <div class="flex items-center p-4 rounded-xl bg-[#FFE24A] w-16 h-16">
                                <img src="{% static 'img/kakao_logo.png' %}" alt="">
                            </div>
                        </a>
                        <a href="{% provider_login_url 'naver' method='oauth2' %}">
                            <div class="flex items-center p-5 text-white rounded-xl bg-[#25D036] w-16 h-16 text-center">
                                <img src="{% static 'img/naver_logo.png' %}" alt="">
                            </div>
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="sm:absolute sm:left-1/2 -translate-x-1/2 bottom-8 animate-bounce text-center mb-16">
            <p class="hidden sm:block">Scroll</p>
            <span class="material-symbols-outlined text-[60px]">expand_more</span>
        </div>
    </section>

    {% comment %} 서비스 소개 {% endcomment %}
    <section class="h-screen bg-gray-200 flex items-center">
        <div class="mx-auto flex flex-col sm:flex-row items-center gap-20 max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="p-5">
                <img src="{% static 'img/식물.png' %}" alt="" class="w-80 h-64 sm:w-[600px] sm:h-[450px]">
            </div>
            <div class="flex flex-col gap-8">
                <p class="text-[25px] sm:text-[45px]"><b>식물 정보 찾고 있나요?</b></p>
                <p class="text-[18px] sm:text-[25px]"><b>작은 화분 식물부터 농작식물까지<br>다양한 식물정보를 제공합니다</b></p>
            </div>
        </div>
    </section>

    <section class="h-screen bg-white flex items-center">
        <div class="mx-auto flex flex-col-reverse sm:flex-row items-center gap-20 max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="flex flex-col gap-8">
                <p class="text-[25px] sm:text-[45px]"><b>식물관리 어려우신가요?</b></p>
                <p class="text-[18px] sm:text-[25px]"><b>식물 품종 데이터를 통한<br>맞춤관리 서비스를 체험해 보세요</b></p>
            </div>
            <div class="p-5">
                <img src="{% static 'img/식집사.jpg' %}" alt="" class="w-80 h-64 sm:w-[600px] sm:h-[450px]">
            </div>
        </div>
    </section>

    <section class="h-screen bg-gray-200 flex items-center">
        <div class="mx-auto flex flex-col sm:flex-row items-center gap-20 max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="p-5 bg-white rounded-xl border shadow-lg">
                <img src="{% static 'img/그린샵.JPG' %}" alt="" class="w-80 h-56 sm:w-[520px] sm:h-[320px]">
            </div>
            <div class="flex flex-col gap-8">
                <p class="text-[25px] sm:text-[45px]"><b>식물 및 관리용품 구매는?</b></p>
                <p class="text-[18px] sm:text-[25px]"><b>필요한 관리용품과 반려식물 및<br>선물용 식물을 구매해 보세요</b></p>
            </div>
        </div>
    </section>
    <section class="bg-white h-28 sm:h-44 w-full flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-10 px-4">
        <div class="bg-[#1EB564] text-white rounded-lg sm:rounded-xl p-2 px-5 w-full sm:w-fit sm:text-[25px] text-center hover:bg-green-700"><a href="{% url 'accounts:signup' %}"><b>회원가입</b></a></div>
        <div class="bg-[#1EB564] text-white rounded-lg sm:rounded-xl p-2 px-5 w-full sm:w-fit sm:text-[25px] text-center hover:bg-green-700"><a href="{% url 'accounts:login' %}"><b>로그인</b></a></div>
    </section>
</main>
{% endblock content %}


{% block script %}{% endblock script %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block head %}
<title>검색</title>
{% endblock head %}


{% block content %}
<main>
    <p class="sticky top-[66px] text-[18px] w-full bg-white py-2 sm:px-6 lg:px-80 border-0 border-b-[1px] z-20"><b>"{{ query }}"</b>(으)로 검색한 결과입니다.</p>
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">

        {% comment %} <div id="carouselExampleControls" class="relative" data-te-carousel-init data-te-carousel-slide>
            <!--Carousel items-->
            <div class="relative w-full overflow-hidden after:clear-both after:block after:content-['']">
                <!--First item-->
                <div class="relative float-left -mr-[100%] w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none" data-te-carousel-item data-te-carousel-active>
                    <img src="https://mdbcdn.b-cdn.net/img/new/slides/041.webp" class="block w-full" alt="Wild Landscape" />
                </div>
                <!--Second item-->
                <div class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none" data-te-carousel-item>
                    <img src="https://mdbcdn.b-cdn.net/img/new/slides/042.webp" class="block w-full" alt="Camera" />
                </div>
                <!--Third item-->
                <div class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none" data-te-carousel-item>
                    <img src="https://mdbcdn.b-cdn.net/img/new/slides/043.webp" class="block w-full" alt="Exotic Fruits" />
                </div>
            </div>
    
            <!--Carousel controls - prev item-->
            <button class="absolute bottom-0 left-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none" type="button" data-te-target="#carouselExampleControls" data-te-slide="prev">
                <span class="inline-block h-8 w-8">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
                    </svg>
                </span>
                <span class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Previous</span>
            </button>
            <!--Carousel controls - next item-->
            <button class="absolute bottom-0 right-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none" type="button" data-te-target="#carouselExampleControls" data-te-slide="next">
                <span class="inline-block h-8 w-8">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                    </svg>
                </span>
                <span class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Next</span>
            </button>
        </div> {% endcomment %}
            
        <!-- 식물 검색결과 -->
        <section class="mt-10">
            <div class='mb-5 font-semibold text-[18px]'>식물 <span class="text-gray-500">({{ search_result_plants|length }})</span></div>
            {% if search_result_plants %}
            <div class="grid grid-cols-5 gap-5 mb-16">
                {% for plant in search_result_plants %}
                <a href="{% url 'plants:detail' plant.pk %}">
                    <div class="flex flex-col gap-3">
                        <div class="relative rounded-lg h-48 border overflow-hidden">
                            <img src="{{ plant.plant_images.first.image.url }}" alt="" class="w-full h-full object-cover duration-200 ease-linear hover:scale-105">
                            <div class="text-[12px] text-white w-fit rounded-md p-1 px-2 shadow-lg absolute top-2 left-2 {% if plant.category == "['실내식물']" %}bg-[#439A3C]{% elif plant.category == "['실외식물']" %}bg-[#9D9441]{% elif plant.category == "['실내식물', '실외식물']" %}bg-[#35493D]{% endif %}">{% if plant.category == "['실내식물']" %}실내{% elif plant.category == "['실외식물']" %}실외{% elif plant.category == "['실내식물', '실외식물']" %}실내, 실외{% endif %}</div>
                        </div>
                        <div class="flex items-center justify-between px-2">
                            <h1 class="font-semibold">{{ plant.title }}</h1>
                            <div class="flex items-center gap-1">
                                <span class="material-symbols-outlined text-[16px] mt-[0.5px]">favorite</span>
                                <span id="garden-like-count">{{ plant.like_users.all|length }}</span>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
            {% else %}
            <div class="w-full h-36 flex items-center justify-center rounded-xl bg-gray-100 text-gray-500">
                검색된 식물이 없습니다.
            </div>
            {% endif %}
        </section>
        

        <!-- 식물원 검색결과 -->
        <section class="mt-16">
            <div class='mb-5 font-semibold text-[18px]'>식물원 <span class="text-gray-500">({{ search_result_gardens|length }})</span></div>
            {% if search_result_gardens %}
            <div class="grid grid-cols-4 gap-5 mb-16">
                {% for garden in search_result_gardens %}
                <a href="{% url 'gardens:detail' garden.pk %}">
                    <div class="flex flex-col gap-3">
                        <div class="relative rounded-lg h-48 border overflow-hidden">
                            <img src="{{garden.image.url}}" alt="" class="w-full h-full object-cover duration-200 ease-linear hover:scale-105">
                            <div class="absolute top-2 left-2 text-[12px] text-gray-700 bg-white border border-[1px] border-gray-400 w-fit rounded-md p-[2px] px-[4px] mb-2 shadow-sm">{{ garden.category }}</div>
                        </div>
                        <div class="px-2">
                            <h1 class="font-semibold">{{ garden.title }}</h1>
                            <p class="text-gray-700 text-[14px]">{{ garden.address }}</p>
                            
                            <div class="flex items-center gap-3 mt-3">
                                <div class="flex items-center gap-1">
                                    <span class="material-symbols-outlined text-[16px] mt-[0.5px]">favorite</span>
                                    <span id="garden-like-count">{{ garden.like_users.all|length }}</span>
                                </div>
                                <div class="flex items-center gap-1">
                                    <span class="material-symbols-outlined text-[16px] mt-[0.5px]">chat_bubble</span>
                                    <span>{{ garden.comments.all|length }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
            {% else %}
            <div class="w-full h-36 flex items-center justify-center rounded-xl bg-gray-100 text-gray-500">
                검색된 식물원이 없습니다.
            </div>
            {% endif %}
        </section>
    
    
        <!-- 관리용품 검색결과 -->
        <section class="my-16">
            <div class='mb-5 font-semibold text-[18px]'>관리용품 <span class="text-gray-500">({{ search_result_sales|length }})</span></div>
            {% if search_result_sales %}
            <div class="grid grid-cols-4 gap-8 mb-16">
                {% for product in search_result_sales %}
                <a href="{% url 'sales:detail' product.pk %}">
                    <div class="w-full mb-5 flex gap-5">
                      <div class="flex flex-col gap-3">
                        <div class="rounded-xl border overflow-hidden relative">
                          <img src="{{ product.Thumbnail.url}}" alt="" class="w-full h-full object-cover duration-200 ease-linear hover:scale-105">
          
                        </div>
                        <strong class='card--name'>{{ product.title }}</strong>
                        <div class="flex items-center justify-between px-2">
                          <h3 class="text-[16px] font-semibold">가격 {{ product.price|intcomma }}</h3>
                          
                          <div class="flex items-center gap-2">
                            <span class="material-symbols-outlined text-[16px] mt-[0.5px]">favorite</span>
                            <span id="garden-like-count">좋아요 {{ product.like.count }}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </a>
                {% endfor %}
        
            </div>
            {% else %}
            <div class="w-full h-36 flex items-center justify-center rounded-xl bg-gray-100 text-gray-500">
                검색된 소모품이 없습니다.
            </div>
            {% endif %}
        </section>
    </div>
</main>

{% endblock content %}


{% block script %}

{% endblock script %}