game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('', views.index, name='index'),
    path('play/', views.play_puzzle, name='play_puzzle'),
    path('solved/', views.solved_puzzles, name='solved_puzzles'),
]

mureok/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('home/', views.home, name='home'),
    path('test/', views.test, name='test'),
    path('search/',views.search, name='search'),
    path('admin/', admin.site.urls),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('communities/', include('communities.urls')),
    path('gardens/', include('gardens.urls')),
    path('plants/', include('plants.urls')),
    path('sales/', include('sales.urls')),
    path('managements/', include('managements.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('game/', include('game.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plants/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'plants'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name = 'create'),
    path('<int:plant_pk>/update/', views.update, name = 'update'),
    path('<int:plant_pk>/delete/', views.delete, name = 'delete'),
    path('<int:plant_pk>/', views.detail, name='detail'),
    path('<int:plant_pk>/likes/', views.likes, name='likes'),

    path('search/', views.search, name='search'),
    path('filter-plants/<str:tag>/', views.filter_plants, name='filter_plants'),
    # path('filter-plants-ajax/', views.filter_plants_ajax, name='filter_plants_ajax'),

    path('recommendation/', views.recommendation, name='recommendation'),
    path('category/', views.category_plants, name='category'),
]

plants/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit, ResizeToFill
from taggit.managers import TaggableManager


# Create your models here.
class Plant(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=460)
    allergy = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    watering = models.CharField(max_length=20)
    sunlight = models.CharField(max_length=20)
    humidity = models.CharField(max_length=20)
    temperature = models.CharField(max_length=20)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_plants')
    tags = TaggableManager(blank=True)
    price = models.IntegerField()

    def __str__(self):
        return self.title

class PlantImage(models.Model):
    def default_image():
        return "default_image_path.jpg"
    
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE, related_name="plant_images")
    image = ProcessedImageField(
        upload_to="plants/images",
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 90},
        blank = False,
        default=default_image,
    )

plants/forms.py
from django import forms
from .models import Plant, PlantImage
from taggit.forms import TagField, TagWidget


class PlantImageForm(forms.ModelForm):
    class Meta:
        model = PlantImage
        fields = ['image']
        widgets = {
            'image': forms.ClearableFileInput(),
        }

class PlantForm(forms.ModelForm):
    title = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class':'w-80 bg-white border-[1px] p-1 px-2 rounded-lg focus:outline-none focus:border-[#1EB564] focus:border-[2px]',
                'id': 'title',
                'placeholder': '식물 이름을 입력해주세요',
            }
        )
    )
    content = forms.CharField(
        label='설명',
        widget=forms.Textarea(
            attrs={
                'class':'w-full h-60 bg-white border-[1px] p-1 px-2 rounded-lg focus:outline-none focus:border-[#1EB564] focus:border-[2px]',
                'id': '설명글',
                'placeholder': '설명글을 입력해주세요',
            }
        ),
    )


    Allergy_CHOICES = [
        ('yes', '꽃가루 알러지 있음'),
        ('no', '꽃가루 알러지 없음'),
    ]

    allergy = forms.ChoiceField(
        label='알레르기',
        widget=forms.RadioSelect(
            attrs={
                'id': 'allergy',
            }
        ),
        choices=Allergy_CHOICES,
    )


    CATEGORY_CHOICE = [
        ('실내식물', '실내식물'), ('실외식물', '실외식물'),
    ]

    category = forms.MultipleChoiceField(
        label = '카테고리',
        widget = forms.CheckboxSelectMultiple(attrs={
            'id': 'category',
        }),
        choices= CATEGORY_CHOICE,
    )

    WATERING_CHOICE = [
        ('주1~2회', '주1~2회'), ('주2~3회', '주2~3회'), ('주3~4회', '주3~4회'),
        ('주4~5회', '주4~5회'), ('월1~2회', '월1~2회'), ('월1회이하', '월1회이하')
    ]

    watering = forms.MultipleChoiceField(
        label = '물 주기',
        widget= forms.CheckboxSelectMultiple(attrs={
            'id': 'watering',
            'class': 'w-full flex-wrap',
        }),
        choices=WATERING_CHOICE,
    )

    SUNLIGHT_CHOICE = [
        ('양지', '양지'), ('반양지', '반양지'), ('반음지', '반음지'), ('음지', '음지'),
    ]

    sunlight = forms.MultipleChoiceField(
        label = '일조량',
        widget= forms.CheckboxSelectMultiple(attrs={
            'id': 'sunlight',
            'class': 'w-full flex-wrap flex gap-5 sm:gap-0',
        }),
        choices=SUNLIGHT_CHOICE,
    )

    HUMIDITY_CHOICE = [
        ('40%이하', '40%이하'), ('40~70%', '40~70%'), ('70~90%', '70~90%'),
    ]

    humidity = forms.MultipleChoiceField(
        label = '습도',
        widget= forms.CheckboxSelectMultiple(attrs={
            'id': 'humidity',
        }),
        choices=HUMIDITY_CHOICE,
    )

    TEMPERATURE_CHOICE = [
        ('18~28도', '18~28도'), ('16~27도', '16~27도'), ('21~25도', '21~25도'),
    ]

    temperature = forms.MultipleChoiceField(
        label = '온도',
        widget = forms.CheckboxSelectMultiple(attrs={
            'id': 'temperature',
        }),
        choices= TEMPERATURE_CHOICE,
    )

    images = forms.FileField(
        label = '이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'w-80 bg-white border rounded-md focus:outline-none focus:ring-1 focus:ring-[#1EB564] text-gray-400',
            }
        )
    )

    tags = forms.CharField(
        label='태그',
        widget=TagWidget(
            attrs={
                'class': 'w-80 bg-white border-[1px] p-1 px-2 rounded-lg focus:outline-none focus:border-[#1EB564] focus:border-[2px]',
                'placeholder': '태그는 콤마(,)로 구분하여 작성해주세요',
            }
        )
    )

    price = forms.IntegerField(  # 가격 필드 추가
        label='가격',
        widget=forms.NumberInput(
            attrs={
                'class': 'w-80 bg-white border-[1px] p-1 px-2 rounded-lg focus:outline-none focus:border-[#1EB564] focus:border-[2px]',
                'id': 'price',
                'placeholder': '가격을 입력해주세요',
            }
        ),
    )
    class Meta:
        model = Plant
        fields = ('title', 'content', 'allergy', 'category', 'watering', 'sunlight', 'humidity', 'temperature', 'price','images', 'tags',)

plants/views.py
from django.shortcuts import render, redirect
from .models import Plant, PlantImage
from .forms import PlantForm, PlantImageForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Count
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from sales.models import Product


# Create your views here.
def index(request):
    plants = Plant.objects.order_by('-id')
    paginator = Paginator(plants, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    unique_tags = []
    all_tags = []
    for plant in page_obj:
        for tag in plant.tags.all():
            if tag.name not in all_tags:
                all_tags.append(tag.name)
                unique_tags.append(tag.name)

    context = {
        'page_obj': page_obj,
        'unique_tags': unique_tags[:10],
        'room_name': "broadcast",
    }
    return render(request, 'plants/index.html', context)



@login_required(login_url='admin:login')
def create(request):

    if not request.user.is_superuser:
        return redirect('home')
    
    if request.method == 'POST':
        tags = request.POST.get('tags').split(',')
        form = PlantForm(request.POST, request.FILES)
        if form.is_valid():
            plant = form.save(commit=False)
            plant.user = request.user
            plant.save()

            images = request.FILES.getlist('images')
            for image in images:
                PlantImage.objects.create(plant=plant, image=image)
            
            for tag in tags:
                plant.tags.add(tag.strip())
            return redirect('plants:detail', plant.pk)
    else:
        form = PlantForm()
        imageForm = PlantImageForm()
    context = {
        'form':form,
        'imageForm':imageForm,
        'room_name': "broadcast"
    }
    return render(request, 'plants/create.html', context)



def update(request, plant_pk):
    
    if not request.user.is_superuser:
        return redirect('home')
    
    plant = Plant.objects.get(pk=plant_pk)
    if request.method == 'POST':
        form = PlantForm(request.POST, request.FILES, instance=plant)
        if form.is_valid():
            form.save()
            plant.tags.clear()
            tags = request.POST.get('tags').split(',')
            for tag in tags:
                plant.tags.add(tag.strip())
            return redirect('plants:detail', plant_pk)
    else:
        form = PlantForm(instance=plant)
    context = {
        'form':form,
        'plant_pk':plant_pk,
        'plant':plant,
        'room_name': "broadcast"
    }
    return render(request, 'plants/update.html', context)



def delete(request, plant_pk):
    
    if not request.user.is_superuser:
        return redirect('home')
    
    plant = Plant.objects.get(pk=plant_pk)
    if request.user == plant.user:
        plant.delete()
    return redirect('plants:index')


def detail(request, plant_pk):
    plant = Plant.objects.get(pk=plant_pk)

    def extract_list(field):
        if plant is not None and "[" in field:
            word = ""
            for item in field:
                if item in ["[", "'", ",", "]"]:
                    continue
                else:
                    word += item
            return word.split()
        else:
            return []
        
    category_list = extract_list(plant.category)
    watering_list = extract_list(plant.watering)
    sunlight_list = extract_list(plant.sunlight)
    humidity_list = extract_list(plant.humidity)
    temperature_list = extract_list(plant.temperature)
    allergy = plant.allergy


    # filtered_products = []
    # products = Product.objects.all()
    
    # print(products)
    # product_title = []
    # for product in products:
    #     tags = product.tags.all()
    #     for tag in tags:
    #         if '따뜻한' in tag.name:
    #             product_title.append(product.title)
    # print(product_title)

        # 위에서는 나오는데 아래서 안나오네요
    # product_titles = []
    # if watering_list == '주1~2회':
    #     products = Product.objects.all()
    #     products = Product.objects.filter(tags__name='따뜻한')
    #     for product in products:
    #         print(product.title)


    # watering_plants = Plant.objects.filter(watering='주1~2회')
    # watering_products = Product.objects.filter(tags_name='따뜻한', plant__in=watering_plants)

    # product_titles = []
    # filtered_products = Product.objects.filter(tags__name__in='따뜻한')
  
    # if plant.watering == '주1~2회':
    #     for product in products:
       
    #         tags = product.tags.all()
    #         for tag in tags:
    #             if '따뜻한' in tag.name: # 이건 product
    #                 product_titles.append(product.title)
    #         # elif watering_list == '월1~2회':
    #         #     if '월1~2회 태그' in product.tags:
    #         #         filtered_products.append(product)
    #         # elif watering_list == '월1회이하':
    #         #     if '월1회이하 태그' in product.tags:
    #         #         filtered_products.append(product)
    #         # elif watering_list == '주2~3회':
    #         #     if '주2~3회 태그' in product.tags:
    #         #         filtered_products.append(product)

    products = Product.objects.all()
   

    context = {
        'plant': plant,
        'category_list': category_list,

        'watering_list': watering_list,
        'sunlight_list': sunlight_list,
        'humidity_list': humidity_list,
        'temperature_list': temperature_list,
        'allergy': allergy,
        'products':products,
    }
    return render(request, 'plants/detail.html', context)


@login_required
def likes(request, plant_pk):
    plant = Plant.objects.get(pk=plant_pk)

    if request.user in plant.like_users.all():
        plant.like_users.remove(request.user)
        is_liked=False
    else:
        plant.like_users.add(request.user)
        is_liked=True

    context = {
        'is_liked' : is_liked,
        'like_count': plant.like_users.count(),
    }
    return JsonResponse(context)


def recommendation(request):
    recommended_plants = Plant.objects.annotate(like_count=Count('like_users')).order_by('-like_count')  # 좋아요 순으로 정렬
    context = {
        'recommended_plants': recommended_plants,
        'room_name': "broadcast"
    }
    return render(request, 'plants/recommendation.html', context)


def search(request):
    query = request.GET.get('searched', '')
    plants = Plant.objects.filter(title__contains=query)

    context = {
        'plants':plants,
        'query':query,
        'room_name': "broadcast"
    }
    return render(request, 'plants/search.html', context)


def filter_plants(request, tag):
    filtered_plants = Plant.objects.filter(tags__name__in=[tag])
    unique_tags = Plant.objects.values_list('tags__name', flat=True).distinct()

    context = {
        'filtered_plants': filtered_plants,
        'unique_tags': unique_tags,
        'room_name': "broadcast"
    }

    return render(request, 'plants/filter.html', context)


def category_plants(request):
    category = request.GET.getlist('category')

    if '전체' in category:
        filtered_plants = Plant.objects.all()
    elif '실내식물' in category:
        filtered_plants = Plant.objects.filter(category__contains='실내식물')
    elif '실외식물' in category:
        filtered_plants = Plant.objects.filter(category__contains='실외식물')
    else:
        filtered_plants = Plant.objects.none()

    context = {
        'filtered_plants': filtered_plants,
        'category': category,
    }
    return render(request, 'plants/category.html', context)

plants/templates/plants/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
  <div class="sm:hidden h-14 px-2 flex items-center">
    <div class="flex flex-shrink-0 items-center gap-4">
        <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
        <p class="text-xl h-8 w-auto"><b>식물</b></p>
    </div>
  </div>
  <div class="flex items-center justify-between border-0 border-b-[1px] border-gray-400 bg-white py-3 my-5 sticky top-0 sm:top-[60px] z-10">
    <div class="flex gap-5 sm:gap-10">
      <div class='text-gray-400 hover:text-black'>
        <a href="{% url 'plants:category' %}?category=전체">
          <span class="{% if category == '전체' %}text-black font-semibold{% endif %}">전체</span>
        </a>
      </div>
      <div class='text-gray-400 hover:text-black'>
        <a href="{% url 'plants:category' %}?category=실내식물">
          <span class="{% if category == '실내식물' %}text-black font-semibold{% endif %}">실내식물</span>
        </a>
      </div>
      <div class='text-gray-400 hover:text-black'>
        <a href="{% url 'plants:category' %}?category=실외식물">
          <span class="{% if category == '실외식물' %}text-black font-semibold{% endif %}">실외식물</span>
        </a>
      </div>
    </div>
  </div>
  {% if filtered_plants %}
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 sm:gap-8 mb-10 min-h-[350px]">
    {% for plant in filtered_plants %}
      <a href="{% url 'plants:detail' plant.pk %}">
        <div class="w-full mb-5 flex flex-col gap-3">
          <div class="rounded-xl border overflow-hidden relative">
            <img src="{{ plant.plant_images.first.image.url }}" alt="" class="w-full h-full object-contain duration-200 ease-linear hover:scale-105">
            
            <div class="text-[12px] text-white w-fit rounded-md p-1 px-2 shadow-lg absolute top-2 left-2 {% if '실내식물' in plant.category and '실외식물' in plant.category %}bg-[#35493D]{% elif '실내식물' in plant.category %}bg-[#439A3C]{% elif '실외식물' in plant.category %}bg-[#9D9441]{% endif %}">
              {% if '실내식물' in plant.category and '실외식물' in plant.category %}
                실내, 실외
              {% elif '실내식물' in plant.category %}
                실내
              {% elif '실외식물' in plant.category %}
                실외
              {% endif %}
            </div>
          </div>
          <div class="flex items-center justify-between px-2">
            <h3 class="text-[16px] font-semibold w-24 whitespace-nowrap overflow-hidden truncate">{{ plant.title }}</h3>

            <div class="flex items-center gap-2">
              <span class="material-symbols-outlined text-[16px] mt-[0.5px]">favorite</span>
              <span id="garden-like-count">{{ plant.like_users.all|length }}</span>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
    {% else %}
    <div class="w-full h-96 flex justify-center items-center">
      식물이 없습니다.
    </div>
    {% endif %}
  </div>
    {% endblock content %}

plants/templates/plants/create.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<title>식물 등록</title>
<link rel="stylesheet" href="{% static 'css/plants_create.css' %}">
{% endblock head %}


{% block content %}
<main class="bg-gray-50">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="sm:hidden h-14 px-2 flex items-center">
    <div class="flex flex-shrink-0 items-center gap-4">
        <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
        <p class="text-xl h-8 w-auto"><b>식물</b></p>
    </div>
  </div>
  <div class="py-10 sm:px-24">
    <a href="{% url 'plants:index' %}" class="w-fit text-[14px] text-gray-500 hover:text-black"><p class="mb-3">식물 돌아가기</p></a>
    <h1 class="text-[25px] font-semibold mb-10">식물 등록</h1>
    <form action="{% url 'plants:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
    
      {% comment %} 이름 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.title.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.title }}</div>
      </div>

      {% comment %} 설명 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.content.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div class="grow">{{ form.content }}</div>
      </div>
      
      {% comment %} 알레르기 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.allergy.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.allergy }}</div>
      </div>

      {% comment %} 카테고리 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.category.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.category }}</div>
      </div>

      {% comment %} 물 주기 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.watering.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.watering }}</div>
      </div>

      {% comment %} 일조량 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.sunlight.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.sunlight }}</div>
      </div>

      {% comment %} 습도 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.humidity.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.humidity }}</div>
      </div>

      {% comment %} 온도 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.temperature.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.temperature }}</div>
      </div>

      {% comment %} 개화시기 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.price.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.price }}</div>
      </div>

      {% comment %} 이미지 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.images.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.images }}</div>
      </div>

      {% comment %} 태그 {% endcomment %}
      <div class="flex sm:flex-row flex-col gap-3 mb-8 w-full">
        <div class="mb-2 w-full sm:w-2/12">{{ form.tags.label }} <span class="text-red-600 text-[20px]">*</span></div>
        <div>{{ form.tags }}</div>
      </div>

      {% comment %} 생성버튼 {% endcomment %}
      <div class="flex justify-center sm:justify-end w-full">
        <button type="submit" class='rounded-md bg-[#1EB564] text-white p-2 px-4 hover:bg-[#148D4C]'>등록하기</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}


{% block script %}

{% endblock script %}

plants/templates/plants/filter.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>태그검색</title>
{% endblock head %}

{% block content %}
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
  <div class="sm:hidden h-14 px-2 flex items-center">
    <div class="flex flex-shrink-0 items-center gap-4">
        <img class="h-8 w-auto" src="{% static 'img/logo.svg' %}" alt="Your Company">
        <p class="text-xl h-8 w-auto"><b>식물</b></p>
    </div>
  </div>

  <div>
    <div class="font-bold text-[25px] sm:text-3xl mt-5 sm:mt-16">
      <p>어떤 종류의<br>식물을 찾고 있나요?</p>
    </div>
    <div>
      <ul class="flex text-base mt-4">
        <!-- 최대 4개의 태그만 출력하도록 수정 -->
        {% for tag in unique_tags|slice:":4" %}
        <li class="rounded-full py-1 px-2 sm:py-2 sm:px-4 m-2 bg-white border border-gray-500 text-gray-500 cursor-pointer transition-colors duration-300 ease-in-out hover:bg-green-500 hover:text-white"  style="pointer-events: auto;">
          <a href="{% url 'plants:filter_plants' tag %}">#{{ tag }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="mb-8 mt-5">
    <form action="{% url 'plants:search' %}" method="GET">
      <input class="border-b-2 border-[#1EB564] outline-none cursor-blink w-full" type="text" name="searched" placeholder="검색어를 입력해주세요" oninput="toggleSearchButton(this)">
    </form>
  </div>
  
  {% if filtered_plants %}
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 sm:gap-8 mb-10 min-h-[350px]">
    {% for plant in filtered_plants %}
    <a href="{% url 'plants:detail' plant.pk %}">
      <div class="w-full mb-5 flex gap-5">
        <div class="flex flex-col gap-3">
          <div class="rounded-xl border overflow-hidden relative">
            <img src="{{ plant.plant_images.first.image.url }}" alt="" class="w-full h-full object-cover duration-200 ease-linear hover:scale-105">
            
            <div class="text-[12px] text-white w-fit rounded-md p-1 px-2 shadow-lg absolute top-2 left-2 {% if plant.category == "['실내식물']" %}bg-[#439A3C]{% elif plant.category == "['실외식물']" %}bg-[#9D9441]{% elif plant.category == "['실내식물', '실외식물']" %}bg-[#35493D]{% endif %}">{% if plant.category == "['실내식물']" %}실내{% elif plant.category == "['실외식물']" %}실외{% elif plant.category == "['실내식물', '실외식물']" %}실내, 실외{% endif %}</div>
          </div>
          <div class="flex items-center justify-between px-2">
            <h3 class="text-[16px] font-semibold w-24 whitespace-nowrap overflow-hidden truncate">{{ plant.title }}</h3>

            <div class="flex items-center gap-2">
              <span class="material-symbols-outlined text-[16px] mt-[0.5px]">favorite</span>
              <span id="garden-like-count">{{ plant.like_users.all|length }}</span>
            </div>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
  {% else %}
  <div class="w-full h-96 flex justify-center items-center">
    식물이 없습니다
  </div>
  {% endif %}
</div>

{% endblock content %}

{% block script %}

{% endblock script %}